{
  config,
  lib,
  pkgs,
  ...
}:
with lib;
let
  cfg = config.fool.reasonix;
  settings = cfg.settings;

  # TOML 裸键只允许 [A-Za-z0-9_-]；含 `.` 等字符的键（如模型名）必须加引号，
  # 否则会被解析成嵌套表。
  tomlKey = key: if builtins.match "[A-Za-z0-9_-]+" key != null then key else builtins.toJSON key;

  # TOML 标量/内联表序列化。字符串、布尔与数字统一走 builtins.toJSON：
  # Nix 的 toString 会把 float 格式化成六位小数，价格 0.1 会变成 0.100000。
  tomlValue =
    value:
    if isList value then
      "[${concatMapStringsSep ", " tomlValue value}]"
    else if isAttrs value then
      "{ ${concatStringsSep ", " (mapAttrsToList (k: v: "${tomlKey k} = ${tomlValue v}") value)} }"
    else
      builtins.toJSON value;

  # 未设置的字段（null）直接省略，避免生成 `field = null` 这类非法 TOML。
  field = name: value: if value == null then "" else "${name} = ${tomlValue value}";

  renderFields = fields: concatStringsSep "\n" (filter (line: line != "") fields);

  tomlPrimitive = types.oneOf [
    types.str
    types.int
    types.float
    types.bool
  ];

  providerType = types.submodule {
    options = {
      name = mkOption {
        type = types.str;
        description = "provider 名称，供 default_model 的 `<provider>/<model>` 前缀引用";
      };
      kind = mkOption {
        type = types.str;
        default = "openai";
        description = "provider 协议类型";
      };
      baseUrl = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "API base_url";
      };
      model = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "单模型 provider 的模型名";
      };
      models = mkOption {
        type = types.nullOr (types.listOf types.str);
        default = null;
        description = "多模型 provider 的模型列表";
      };
      defaultModel = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "多模型 provider 的默认模型（TOML 键 `default`）";
      };
      apiKeyEnv = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "读取 API key 的环境变量名；密钥本身不进入 Nix store";
      };
      balanceUrl = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "钱包余额查询端点";
      };
      contextWindow = mkOption {
        type = types.nullOr types.int;
        default = null;
        description = "上下文窗口 token 数";
      };
      maxOutputTokens = mkOption {
        type = types.nullOr types.int;
        default = null;
        description = "单次输出 token 上限；null 表示沿用服务端默认";
      };
      price = mkOption {
        type = types.nullOr (types.attrsOf tomlPrimitive);
        default = null;
        description = "provider 级兜底价格（每 1M token），如 { cache_hit = 0.1; input = 3; output = 9; currency = \"¥\"; }";
      };
      prices = mkOption {
        type = types.nullOr (types.attrsOf (types.attrsOf tomlPrimitive));
        default = null;
        description = "按模型覆盖的价格表";
      };
      billingCurrency = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "计费货币，如 \"CNY\"";
      };
      visionModels = mkOption {
        type = types.nullOr (types.listOf types.str);
        default = null;
        description = "该 provider 内支持图片输入的模型";
      };
      effort = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "reasoning effort，如 \"max\"";
      };
    };
  };

  renderProvider =
    p:
    ''
      [[providers]]
      ${renderFields [
        (field "name" p.name)
        (field "kind" p.kind)
        (field "base_url" p.baseUrl)
        (field "model" p.model)
        (field "models" p.models)
        (field "default" p.defaultModel)
        (field "api_key_env" p.apiKeyEnv)
        (field "balance_url" p.balanceUrl)
        (field "context_window" p.contextWindow)
        (field "max_output_tokens" p.maxOutputTokens)
        (field "price" p.price)
        (field "prices" p.prices)
        (field "billing_currency" p.billingCurrency)
        (field "vision_models" p.visionModels)
        (field "effort" p.effort)
      ]}
    '';

  # 只覆盖核心项；bot/desktop/plugins 等交给 extraConfig 或 CLI 自身维护。
  # TOML 要求顶层标量键先于所有表，因此 extraConfig 只能追加表/数组表。
  configText = ''
    # Generated by nixcf (fool.reasonix.settings / fool.reasonix.extraConfig).
    # 种子式写入：目标已存在且未开启 fool.reasonix.config.force 时不会被覆盖。
    config_version    = ${toString settings.configVersion}
    default_model     = ${tomlValue settings.defaultModel}
    language          = ${tomlValue settings.language}
    credentials_store = ${tomlValue settings.credentialsStore}

    [ui]
    theme           = ${tomlValue settings.ui.theme}
    show_turn_usage = ${tomlValue settings.ui.showTurnUsage}

    [agent]
    temperature   = ${tomlValue settings.agent.temperature}
    compact_ratio = ${tomlValue settings.agent.compactRatio}

    [permissions]
    mode = ${tomlValue settings.permissions.mode}

    [sandbox]
    bash    = ${tomlValue settings.sandbox.bash}
    network = ${tomlValue settings.sandbox.network}

    ${concatMapStringsSep "\n" renderProvider settings.providers}${optionalString (
      cfg.extraConfig != ""
    ) cfg.extraConfig}
  '';
in
{
  options.fool.reasonix = {
    config = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = "把 Nix 生成的 config.toml 种子写入 ~/.reasonix/config.toml";
      };
      force = mkOption {
        type = types.bool;
        default = false;
        description = ''
          每次 activation 用 Nix 生成的配置覆盖 ~/.reasonix/config.toml。
          默认 false：仅在文件不存在时写入，CLI 后续修改会被保留。
          覆盖前会备份为 config.toml.bak。
        '';
      };
    };

    settings = {
      configVersion = mkOption {
        type = types.int;
        default = 7;
        description = "Reasonix config schema 版本";
      };
      defaultModel = mkOption {
        type = types.str;
        default = "deepseek-flash/deepseek-v4.1-flash-expires-on-0910";
        description = "默认模型，格式为 `<provider>/<model>`";
      };
      language = mkOption {
        type = types.str;
        default = "zh";
        description = "UI 与模型语言";
      };
      credentialsStore = mkOption {
        type = types.str;
        default = "auto";
        description = "凭证存储方式";
      };
      ui = {
        theme = mkOption {
          type = types.str;
          default = "auto";
          description = "CLI 配色：auto|dark|light";
        };
        showTurnUsage = mkOption {
          type = types.bool;
          default = true;
          description = "在会话中显示每轮的 token 与费用";
        };
      };
      agent = {
        temperature = mkOption {
          type = types.float;
          default = 0.0;
          description = "采样温度";
        };
        compactRatio = mkOption {
          type = types.float;
          default = 0.8;
          description = "自动压缩触发比例";
        };
      };
      permissions = {
        mode = mkOption {
          type = types.str;
          default = "ask";
          description = "写操作未命中规则时的回退策略：ask|allow|deny";
        };
      };
      sandbox = {
        bash = mkOption {
          type = types.str;
          default = "enforce";
          description = "bash 沙箱策略";
        };
        network = mkOption {
          type = types.bool;
          default = true;
          description = "是否允许沙箱内 bash 访问网络";
        };
      };
      providers = mkOption {
        type = types.listOf providerType;
        default = [
          {
            name = "deepseek-flash";
            kind = "openai";
            baseUrl = "https://api.deepseek.com";
            models = [
              "deepseek-v4-flash"
              "deepseek-v4-flash-vision-exp"
              "deepseek-v4.1-flash-expires-on-0910"
            ];
            defaultModel = "deepseek-v4-flash";
            apiKeyEnv = "DEEPSEEK_API_KEY";
            balanceUrl = "https://api.deepseek.com/user/balance";
            contextWindow = 1000000;
            price = {
              cache_hit = 0.1;
              input = 3;
              output = 9;
              currency = "¥";
            };
            prices = {
              "deepseek-v4-flash-vision-exp" = {
                cache_hit = 0.1;
                input = 3;
                output = 9;
                currency = "¥";
              };
              "deepseek-v4.1-flash-expires-on-0910" = {
                cache_hit = 0.1;
                input = 3;
                output = 9;
                currency = "¥";
              };
            };
            billingCurrency = "CNY";
            visionModels = [
              "deepseek-v4-flash-vision-exp"
              "deepseek-v4.1-flash-expires-on-0910"
            ];
          }
          {
            name = "deepseek-pro";
            kind = "openai";
            baseUrl = "https://api.deepseek.com";
            model = "deepseek-v4-pro";
            apiKeyEnv = "DEEPSEEK_API_KEY";
            balanceUrl = "https://api.deepseek.com/user/balance";
            contextWindow = 1000000;
            price = {
              cache_hit = 0.3;
              input = 9;
              output = 27;
              currency = "¥";
            };
            billingCurrency = "CNY";
            effort = "max";
          }
          {
            name = "scnet-d4f0426";
            kind = "openai";
            baseUrl = "https://api.scnet.cn/api/llm/v1";
            model = "DeepSeek-V4-Flash";
            apiKeyEnv = "SCNET_API_KEY";
            contextWindow = 1000000;
            price = {
              cache_hit = 0.2;
              input = 1;
              output = 2;
              currency = "¥";
            };
            billingCurrency = "CNY";
            effort = "max";
          }
        ];
        description = "provider 列表，渲染为 [[providers]] 数组表";
      };
    };

    extraConfig = mkOption {
      type = types.lines;
      default = "";
      description = ''
        原文透传到 config.toml 末尾，用于 [bot]、[desktop]、[[plugins]] 等未 Nix 化的表。
        注意：TOML 顶层标量键必须写在所有表之前，这里只能追加表/数组表，
        顶层键请改用 fool.reasonix.settings。
      '';
    };

    configFile = mkOption {
      type = types.package;
      internal = true;
      description = "生成的 config.toml（store 路径），供 activation 与调试使用";
    };
  };

  config = mkIf cfg.enable {
    fool.reasonix.configFile = pkgs.writeText "reasonix-config.toml" configText;

    home.activation.reasonix-config = mkIf cfg.config.enable (
      lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        reasonixDir="$HOME/.reasonix"
        reasonixFile="$reasonixDir/config.toml"
        reasonixForce="${if cfg.config.force then "1" else "0"}"
        if [[ -e "$reasonixFile" && "$reasonixForce" != "1" ]]; then
          $VERBOSE_ECHO "keeping existing $reasonixFile (set fool.reasonix.config.force = true to overwrite)"
        else
          $DRY_RUN_CMD mkdir -p -m 0700 "$reasonixDir"
          if [[ -e "$reasonixFile" ]]; then
            $DRY_RUN_CMD cp -f "$reasonixFile" "$reasonixFile.bak"
            $VERBOSE_ECHO "backed up existing Reasonix config to $reasonixFile.bak"
          fi
          $DRY_RUN_CMD install -m 0600 ${cfg.configFile} "$reasonixFile"
          $VERBOSE_ECHO "seeded $reasonixFile from ${cfg.configFile}"
        fi
      ''
    );
  };
}
